version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dt_rails_development
      MYSQL_USER: rails
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql2://rails:password@db:3306/dt_rails_development
      RAILS_ENV: development
    stdin_open: true
    tty: true

volumes:
  mysql_data:
  bundle_cache:
