# Redis configuration
default: &default
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/0" } %>
  timeout: 1
  reconnect_attempts: 3

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

production:
  <<: *default
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/0" } %>
