# frozen_string_literal: true

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use Amazon S3 to store uploaded files (see "Other cloud providers" below for more options).
#
# amazon:
#   service: S3
#   access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
#   secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
#   region: your-region
#   bucket: your-bucket-name

# Use local disk to store uploaded files (see "Other cloud providers" below for more options).
#
# local:
#   service: Disk
#   root: <%= Rails.root.join("storage") %>

# Use Microsoft Azure Storage to store uploaded files (see "Other cloud providers" below for more options).
#
# azure:
#   service: AzureStorage
#   storage_account_name: your-storage-account-name
#   storage_access_key: your-storage-access-key
#   container: your-container-name

# Use Google Cloud Storage to store uploaded files (see "Other cloud providers" below for more options).
#
# google:
#   service: GCS
#   project: your-project-id
#   credentials: <%= Rails.root.join("path/to/gcs-service-account-key.json") %>
#   bucket: your-bucket-name

# Use Cloudinary to store uploaded files (see "Other cloud providers" below for more options).
#
# cloudinary:
#   service: Cloudinary
#   cloud_name: your-cloud-name
#   api_key: your-api-key
#   api_secret: your-api-secret
#   secure: true

# Use Mirror Storage to store uploaded files on multiple storage services.
#
# mirror:
#   service: Mirror
#   primary:
#     service: Disk
#     root: <%= Rails.root.join("storage") %>
#   mirrors:
#     - service: S3
#       bucket: your-bucket-name
#       access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
#       secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
#       region: your-region
#     - service: GCS
#       project: your-project-id
#       credentials: <%= Rails.root.join("path/to/gcs-service-account-key.json") %>
#       bucket: your-bucket-name
